### ISSUE TITLE
Package.json issues

### ISSUE THREAD

**Issue by NathanaelA** [alcoceba/ngCarouselDirective#1]
Your package json file has several issues; 
- Your github link is wrong (goes to a broken missing/broken repo)
- You should have a NativeScript key (otherwise the plugin sites will ignore it)

"nativescript": {
    "platforms": {
      "android": "3.0.0",
      "ios": "3.0.0"
    },
    "plugin": {
      "nan": "true",
      "pan": "false",
      "core3": "true",
      "category": "Interface"
    }
  },

**Comment by alcoceba** [comment]
Thanks for your feedback. I've just fixed it, it should be right now.
