### ISSUE TITLE
Does this support 3.0.1

### ISSUE THREAD

**Issue by URvesh109** [alcoceba/ngCarouselDirective#2]
I am getting this error 

Project successfully created.
Executing before-prepare hook from /home/urvesh/Miscellaneous/Nativescript/Carousel/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.2.2
node_modules/nativescript-ng2-carousel/nativescript-ng2-carousel.directive.ts(102,9): error TS2322: Type 'string' is not assignable to type 'HorizontalAlignment'.

node_modules/nativescript-ng2-carousel/nativescript-ng2-carousel.directive.ts(103,60): error TS2339: Property 'auto' does not exist on type 'typeof GridUnitType'.

node_modules/nativescript-ng2-carousel/nativescript-ng2-carousel.directive.ts(104,63): error TS2339: Property 'star' does not exist on type 'typeof GridUnitType'.

node_modules/nativescript-ng2-carousel/nativescript-ng2-carousel.directive.ts(105,63): error TS2339: Property 'star' does not exist on type 'typeof GridUnitType'.
node_modules/nativescript-ng2-carousel/nativescript-ng2-carousel.directive.ts(125,60): error TS2339: Property 'auto' does not exist on type 'typeof GridUnitType'.
node_modules/nativescript-ng2-carousel/nativescript-ng2-carousel.directive.ts(126,13): error TS2322: Type 'string' is not assignable to type 'Visibility'.
node_modules/nativescript-ng2-carousel/nativescript-ng2-carousel.directive.ts(141,68): error TS2339: Property 'auto' does not exist on type 'typeof GridUnitType'.

node_modules/nativescript-ng2-carousel/nativescript-ng2-carousel.directive.ts(204,13): error TS2322: Type 'string' is not assignable to type 'HorizontalAlignment'.
node_modules/nativescript-ng2-carousel/nativescript-ng2-carousel.directive.ts(220,13): error TS2322: Type 'string' is not assignable to type 'HorizontalAlignment'.

node_modules/nativescript-ng2-carousel/nativescript-ng2-carousel.directive.ts(290,13): error TS2322: Type '"visible" | "collapsed"' is not assignable to type 'Visibility'.
  Type '"collapsed"' is not assignable to type 'Visibility'.

**Comment by URvesh109** [comment]
I have manually change in nativescript-ng2-carousel.directive.ts now it is working fine, best plugin so far
sry for opening issues

**Comment by alcoceba** [comment]
Hi @URvesh109, any feedback is welcome, as well as any suggestions, bugs or changes. I would like to push some new features, so if there are any comments let me know.
