### ISSUE TITLE
Cannot load image from local resource

### ISSUE THREAD

**Issue by kumaran-dena** [alcoceba/ngCarouselDirective#3]
Hi, 

I tried to load image from local resource, but its not working. If i give url means its working perfectly.

FYI, My folder structure is as follows,
![sr2](https://user-images.githubusercontent.com/30895291/30551058-ea16f8ec-9cb6-11e7-8b3a-ecab2a51776d.PNG)

And my code is, 
`this.images = [
            { title: 'Image 1',  file: '~/res/logo.png'  },
            { title: 'Image 2',  url:'https://unsplash.it/400/300/?image=870'}
        ];
`
Please suggest how to refer the image source from local res folder.

Regarding this issue, I have raised the topic on NS community forum [thread](https://discourse.nativescript.org/t/cannot-load-image-from-local-resource-nativescript-ng2-carousel/2608)

Thanks in advance.

**Comment by kumaran-dena** [comment]
i. { title: ‘Image 0’, file: ‘res://logo.png’ }
ii. { title: ‘Image 0’, file: ‘res://logo’ }

I have tried the both of above, But not working.

**Comment by kumaran-dena** [comment]
I tried with creating the assets folder with image, inside app root structure.

Then referred that image as follows,
  {title: 'Image 2', file: '~/assets/carosel_screen.jpg'}
This time its working with local resources.
FYI, My folder structure is!
![sr3](https://user-images.githubusercontent.com/30895291/30578935-f7701c9e-9d33-11e7-8e5e-7af76b967bed.PNG)

But issue with select and load the images from App-Resouces/android/drawable folder.

**Comment by alcoceba** [comment]
Hello @kumaran-dena, the aim of "file" attribute is to add images from assets folder, not resources folder.

Did it finally work setting file: 'res://logo.png'?

**Comment by alcoceba** [comment]
Now "file" attribute supports both images in **assets folder** and images in **resources folders**. To load images from resources folders you must set the resource name in this way **without the image extenison .jpg, .png or whatever**:

`{ title: 'Image 2', file: 'res://image-name' }
`
You can refer the demo or documentation for further details.

**Comment by kumaran-dena** [comment]
@alcoceba Thanks for your recent released version 0.0.5 of this plugin. 

I have updated the plugin version to 0.0.5 in my project. And tested with loading the images from resources folders. Its works as expected. 

FYI,
![carosel](https://user-images.githubusercontent.com/30895291/31373177-a67a1450-adb6-11e7-8739-b6b097dac089.PNG)

Thanks for your support @alcoceba.
